% build_full_chain.m  [클럭 단위]
% TX → Channel → RX 통합 모델 + EVM / BER 측정
%
% BER 측정 원리:
%   RX Frame Sync가 프리앰블 상관으로 프레임 경계를 찾고,
%   헤더에서 frame_cnt를 복조하여 BER Monitor로 전달.
%   BER Monitor는 동일한 PRNG(seed=mod(fc*40503+si*20261,65536))로
%   기준 심볼을 재생성하여 TX 참조 신호 없이 BER을 계산.

mdl     = 'full_chain';
sim_dir = fileparts(mfilename('fullpath'));

if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib = 'simulink/User-Defined Functions/MATLAB Function';

%% ── Sub-models ───────────────────────────────────────────────────────────────
add_block('simulink/Ports & Subsystems/Model', [mdl '/TX Model'], ...
    'ModelName','tx_model','Position',[60 90 200 150]);
add_block('simulink/Ports & Subsystems/Model', [mdl '/Channel Model'], ...
    'ModelName','channel_model','Position',[280 100 420 140]);
add_block('simulink/Ports & Subsystems/Model', [mdl '/RX Model'], ...
    'ModelName','rx_model','Position',[500 85 640 165]);

%% ── Signal Specification ─────────────────────────────────────────────────────
add_block('simulink/Signal Attributes/Signal Specification', [mdl '/Spec1'], ...
    'Dimensions','1', 'Position',[230 110 260 130]);
add_block('simulink/Signal Attributes/Signal Specification', [mdl '/Spec2'], ...
    'Dimensions','1', 'Position',[450 110 480 130]);

%% ── EVM Monitor ──────────────────────────────────────────────────────────────
add_block(lib, [mdl '/EVM Monitor'], 'Position',[720 75 880 125]);
set_fcn(mdl, 'EVM Monitor', ...
    ['function evm_db = fcn(sym, valid)' newline ...
     'persistent err_acc ref_acc evm_out' newline ...
     'if isempty(evm_out)' newline ...
     '    err_acc=double(0); ref_acc=double(1e-10); evm_out=double(-30);' newline ...
     'end' newline ...
     'if valid > 0.5' newline ...
     '    rx_d    = qamdemod(sym, 16, ''UnitAveragePower'', true);' newline ...
     '    ref     = qammod(rx_d, 16, ''UnitAveragePower'', true);' newline ...
     '    err_acc = err_acc + real((sym-ref)*conj(sym-ref));' newline ...
     '    ref_acc = ref_acc + real(ref*conj(ref));' newline ...
     '    evm_out = 10*log10(err_acc / ref_acc);' newline ...
     'end' newline ...
     'evm_db = evm_out;']);

%% ── BER Monitor ──────────────────────────────────────────────────────────────
% 입력 1: data_sym     — RX Frame Sync 출력 심볼 (복소)
% 입력 2: data_valid   — 데이터 유효 플래그 (실수)
% 입력 3: rx_frame_cnt — 헤더에서 복조한 frame_cnt (실수)
%
% TX PRNG 재생성: seed = mod(rx_frame_cnt*40503 + sym_idx*20261, 65536)
% → 4bit 추출 → qammod → qamdemod 인덱스 → rx와 비교
add_block(lib, [mdl '/BER Monitor'], 'Position',[720 145 880 240]);
set_fcn(mdl, 'BER Monitor', ...
    ['function [ser, ber_est, n_syms, n_correct] = fcn(data_sym, data_valid, rx_frame_cnt)' newline ...
     '% frame_cnt 기반 PRNG 재생성으로 TX 참조 없이 BER 측정' newline ...
     '% data_valid=1 : Frame Sync가 프리앰블+헤더CRC 통과한 DATA 구간 심볼' newline ...
     '% data_valid=0 : SEARCH/HEADER 구간 → 측정 안 함' newline ...
     'persistent n_err n_total ser_out ber_out sym_idx cur_frame' newline ...
     'if isempty(n_err)' newline ...
     '    n_err     = int32(0); n_total   = int32(0);' newline ...
     '    ser_out   = double(0); ber_out  = double(0);' newline ...
     '    sym_idx   = int32(0); cur_frame = double(-1);' newline ...
     'end' newline ...
     'ser       = ser_out;' newline ...
     'ber_est   = ber_out;' newline ...
     'n_syms    = double(n_total);' newline ...
     'n_correct = double(n_total - n_err);' newline ...
     'if data_valid < 0.5, return; end' newline ...
     '%% 새 frame_cnt 감지 → sym_idx 리셋 (프레임 경계)' newline ...
     'if rx_frame_cnt ~= cur_frame' newline ...
     '    cur_frame = rx_frame_cnt;' newline ...
     '    sym_idx   = int32(0);' newline ...
     'end' newline ...
     '%% TX PRNG 재생성 — TX QAM Source DATA 구간과 동일' newline ...
     '%% seed = mod(frame_cnt*40503 + sym_idx*20261, 65536)' newline ...
     'si   = double(sym_idx) + 1;' newline ...
     'fc   = cur_frame;' newline ...
     'seed = mod(fc*40503 + si*20261, 65536);' newline ...
     'b0   = mod(floor(seed),     2);' newline ...
     'b1   = mod(floor(seed / 2), 2);' newline ...
     'b2   = mod(floor(seed / 4), 2);' newline ...
     'b3   = mod(floor(seed / 8), 2);' newline ...
     'ref_sym = qammod([b0;b1;b2;b3], 16, ''InputType'',''bit'',''UnitAveragePower'',true);' newline ...
     '%% qamdemod으로 동일 인덱스 공간에서 비교' newline ...
     'rx_idx  = int32(qamdemod(data_sym, 16, ''UnitAveragePower'', true));' newline ...
     'ref_idx = int32(qamdemod(ref_sym,  16, ''UnitAveragePower'', true));' newline ...
     'if rx_idx ~= ref_idx' newline ...
     '    n_err = n_err + int32(1);' newline ...
     'end' newline ...
     'n_total = n_total + int32(1);' newline ...
     'sym_idx = sym_idx + int32(1);' newline ...
     'if n_total > int32(0)' newline ...
     '    ser_out = double(n_err) / double(n_total);' newline ...
     '    ber_out = ser_out / 4;' newline ...
     'end' newline ...
     'ser       = ser_out;' newline ...
     'ber_est   = ber_out;' newline ...
     'n_syms    = double(n_total);' newline ...
     'n_correct = double(n_total - n_err);']);

%% ── Display / Scope ──────────────────────────────────────────────────────────
add_block('simulink/Sinks/Display', [mdl '/EVM (dB)'], ...
    'Position',[940 83 1060 107]);
add_block('simulink/Sinks/Display', [mdl '/SER'], ...
    'Position',[940 150 1060 174]);
add_block('simulink/Sinks/Display', [mdl '/BER est'], ...
    'Position',[940 182 1060 206]);
add_block('simulink/Sinks/Display', [mdl '/N Syms'], ...
    'Position',[940 214 1060 238]);
add_block('simulink/Sinks/Display', [mdl '/N Correct'], ...
    'Position',[940 246 1060 270]);
add_block('simulink/Sinks/Display', [mdl '/RX Frame Cnt'], ...
    'Position',[940 278 1060 302]);

add_block('simulink/Sinks/Scope', [mdl '/Scope TX'], ...
    'Position',[230 300 280 340]);
add_block('simulink/Sinks/Scope', [mdl '/Scope RX'], ...
    'Position',[660 300 710 340]);

%% ── 연결 ─────────────────────────────────────────────────────────────────────
add_line(mdl, 'TX Model/1',      'Spec1/1');
add_line(mdl, 'Spec1/1',         'Channel Model/1');
add_line(mdl, 'Spec1/1',         'Scope TX/1');
add_line(mdl, 'Channel Model/1', 'Spec2/1');
add_line(mdl, 'Spec2/1',         'RX Model/1');

add_line(mdl, 'RX Model/1',      'EVM Monitor/1');   % data_sym
add_line(mdl, 'RX Model/2',      'EVM Monitor/2');   % data_valid
add_line(mdl, 'EVM Monitor/1',   'EVM (dB)/1');
add_line(mdl, 'RX Model/1',      'Scope RX/1');

add_line(mdl, 'RX Model/1',      'BER Monitor/1');   % data_sym
add_line(mdl, 'RX Model/2',      'BER Monitor/2');   % data_valid
add_line(mdl, 'RX Model/3',      'BER Monitor/3');   % rx_frame_cnt
add_line(mdl, 'BER Monitor/1',   'SER/1');
add_line(mdl, 'BER Monitor/2',   'BER est/1');
add_line(mdl, 'BER Monitor/3',   'N Syms/1');
add_line(mdl, 'BER Monitor/4',   'N Correct/1');
add_line(mdl, 'RX Model/3',      'RX Frame Cnt/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');
save_system(mdl, fullfile(sim_dir, 'full_chain.slx'));
fprintf('Saved: full_chain.slx\n');

function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end
