% build_channel_model.m
% Channel: Multipath → Doppler → AWGN
% 모든 블록 입출력 크기 동일 (복소 심볼 벡터)

mdl = 'channel_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 210;

%% Input
add_block('simulink/Sources/In1', [mdl '/TX In'], 'Position',[px 70 px+30 90]);
px = px + step;

%% Multipath — 고정 크기 순환 버퍼 (입출력 크기 동일)
add_block(lib, [mdl '/Multipath'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Multipath', ...
    ['function y = fcn(x)' newline ...
     '% ITU VehA 6-tap, @symbol rate (tap delays: 0,3,7,10,17,25 samples @10MHz)' newline ...
     'tap_d = int32([0 3 7 10 17 25]);' newline ...
     'gains = 10.^([0 -1 -9 -10 -15 -20]/20);' newline ...
     'MAX_D = int32(25);' newline ...
     'persistent buf' newline ...
     'if isempty(buf), buf = complex(zeros(MAX_D+1, 1)); end' newline ...
     'n = numel(x);' newline ...
     'y = complex(zeros(n, 1));' newline ...
     'for i = 1:n' newline ...
     '    buf  = [x(i); buf(1:MAX_D)];' newline ...
     '    s    = complex(0, 0);' newline ...
     '    for k = 1:6' newline ...
     '        h = complex(randn, randn) / sqrt(2);' newline ...
     '        s = s + gains(k) * h * buf(tap_d(k)+1);' newline ...
     '    end' newline ...
     '    y(i) = s;' newline ...
     'end']);
set_complex_output(mdl, 'Multipath');
px = px + step;

%% Doppler — persistent 위상 누적 (입출력 크기 동일)
add_block(lib, [mdl '/Doppler'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Doppler', ...
    ['function y = fcn(x)' newline ...
     'persistent phase' newline ...
     'if isempty(phase), phase = double(0); end' newline ...
     'fs = 10e6; fo = 5000;' newline ...
     'n  = numel(x);' newline ...
     'y  = complex(zeros(n, 1));' newline ...
     'for k = 1:n' newline ...
     '    y(k)  = x(k) * exp(complex(0, phase));' newline ...
     '    phase = phase + 2*pi*fo/fs;' newline ...
     'end']);
set_complex_output(mdl, 'Doppler');
px = px + step;

%% AWGN (입출력 크기 동일)
add_block(lib, [mdl '/AWGN'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'AWGN', ...
    ['function y = fcn(x, EbNo_dB)' newline ...
     'bps       = 4;' newline ...
     'EsNo      = EbNo_dB + 10*log10(double(bps));' newline ...
     'sig_pwr   = mean(abs(x).^2);' newline ...
     'nv        = sig_pwr / (10^(EsNo/10));' newline ...
     'noise     = complex(randn(size(x)), randn(size(x))) * sqrt(nv/2);' newline ...
     'y         = x + noise;']);
set_complex_output(mdl, 'AWGN');
px = px + step;

%% EbNo 상수 입력
add_block('simulink/Sources/Constant', [mdl '/EbNo'], ...
    'Value','10', 'SampleTime','inf', ...
    'Position',[px-step 160 px-step+80 190]);

%% Output
add_block('simulink/Sinks/Out1', [mdl '/RX Out'], 'Position',[px 70 px+30 90]);

%% Connections
add_line(mdl, 'TX In/1',    'Multipath/1');
add_line(mdl, 'Multipath/1','Doppler/1');
add_line(mdl, 'Doppler/1',  'AWGN/1');
add_line(mdl, 'EbNo/1',     'AWGN/2');
add_line(mdl, 'AWGN/1',     'RX Out/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1','StopTime','100');

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'channel_model.slx'));
fprintf('Saved: channel_model.slx\n');

%% Helpers
function set_fcn(mdl, blk_name, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk_name]);
    ch.Script = script;
end

function set_complex_output(mdl, blk_name)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk_name]);
    y  = ch.find('-isa','Stateflow.Data','Name','y');
    if ~isempty(y), y.Complexity = 'On'; end
end
