% build_rx_model.m — Programmatically creates rx_model.slx

mdl = 'rx_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30;
step = 170;
h    = [55 105];   % [top bottom] y positions

%% Input
add_block('simulink/Sources/In1', [mdl '/RX In'], 'Position',[px 70 px+30 90]);
px = px + step;

%% MATLAB Function blocks
blocks = { ...
    'AGC',          'function y=fcn(x); g=sqrt(1/(mean(abs(x).^2)+eps)); y=x*g;'; ...
    'Freq Sync',    ['function y=fcn(x)' newline ...
                     'N=length(x);' newline ...
                     '[~,idx]=max(abs(fft(x.^4,N)));' newline ...
                     'fo=(idx-1)*10e6/N/4;' newline ...
                     't=(0:N-1)''/10e6;' newline ...
                     'y=x.*exp(-1j*2*pi*fo*t);']; ...
    'Timing Sync',  ['function y=fcn(x)' newline ...
                     'sps=4; N=floor(length(x)/sps);' newline ...
                     'y=x(round(sps/2):sps:N*sps);']; ...
    'Phase Sync',   ['function y=fcn(x)' newline ...
                     'alpha=0.05; ph=0; fr=0; y=zeros(size(x));' newline ...
                     'for k=1:length(x)' newline ...
                     '  y(k)=x(k)*exp(-1j*ph);' newline ...
                     '  d=sign(real(y(k)))+1j*sign(imag(y(k)));' newline ...
                     '  e=imag(y(k)*conj(d));' newline ...
                     '  fr=fr+0.0025*e; ph=ph+alpha*e+fr;' newline ...
                     'end']; ...
    'Ch Estimator', 'function y=fcn(x); y=x;'; ...
    'MMSE EQ',      ['function y=fcn(x)' newline ...
                     'H=ones(size(x)); nv=0.01;' newline ...
                     'y=conj(H)./(abs(H).^2+nv).*x;']; ...
    'Demodulator',  'function y=fcn(x); y=double(qamdemod(x,16,''OutputType'',''bit'',''UnitAveragePower'',true));'; ...
    'FEC Decoder',  ['function y=fcn(x)' newline ...
                     'trel=poly2trellis(7,[171 133]);' newline ...
                     'xh=double(x<0);' newline ...
                     'dec=vitdec(xh,trel,34,''cont'',''hard'');' newline ...
                     'y=dec(35:end);'] ...
};

for k = 1:size(blocks,1)
    add_block(lib, [mdl '/' blocks{k,1}], 'Position',[px h(1) px+130 h(2)]);
    set_param([mdl '/' blocks{k,1}], 'MATLABFunction', blocks{k,2});
    px = px + step;
end

%% Output
add_block('simulink/Sinks/Out1', [mdl '/RX Bits'], 'Position',[px 70 px+30 90]);

%% Connections
chain = [{'RX In'}, blocks(:,1)', {'RX Bits'}];
for i = 1:length(chain)-1
    add_line(mdl, [chain{i} '/1'], [chain{i+1} '/1']);
end

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'rx_model.slx'));
fprintf('Saved: rx_model.slx\n');
