% build_full_chain.m  [클럭 단위]
% TX → Channel → RX + EVM / 패턴기반 BER 측정
%
% BER 측정 원리 (패턴 기반 동기):
%   TX: seed=mod(idx*20261+12345,65536) 의 256심볼 반복 PRNG 패턴
%   BER Monitor:
%     1) 동일 패턴 256심볼을 내부에서 미리 생성 (ref_idx_pat)
%     2) RX 수신 256심볼을 버퍼링 후 전수 오프셋(0..255) 탐색
%        → 오류가 가장 적은 오프셋 = 동기 포인트 (sync_offset)
%     3) 동기 확정 후 매 심볼마다 누적 SER/BER 계산

mdl     = 'full_chain';
sim_dir = fileparts(mfilename('fullpath'));

if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib = 'simulink/User-Defined Functions/MATLAB Function';

%% ── Sub-models ───────────────────────────────────────────────────────────────
add_block('simulink/Ports & Subsystems/Model', [mdl '/TX Model'], ...
    'ModelName','tx_model','Position',[60 90 200 150]);

add_block('simulink/Ports & Subsystems/Model', [mdl '/Channel Model'], ...
    'ModelName','channel_model','Position',[280 100 420 140]);

add_block('simulink/Ports & Subsystems/Model', [mdl '/RX Model'], ...
    'ModelName','rx_model','Position',[500 90 640 150]);

%% ── Signal Specification ─────────────────────────────────────────────────────
add_block('simulink/Signal Attributes/Signal Specification', [mdl '/Spec1'], ...
    'Dimensions','1', 'Position',[230 110 260 130]);
add_block('simulink/Signal Attributes/Signal Specification', [mdl '/Spec2'], ...
    'Dimensions','1', 'Position',[450 110 480 130]);

%% ── EVM Monitor ──────────────────────────────────────────────────────────────
add_block(lib, [mdl '/EVM Monitor'], 'Position',[720 75 880 125]);
set_fcn(mdl, 'EVM Monitor', ...
    ['function evm_db = fcn(sym, valid)' newline ...
     'persistent err_acc ref_acc evm_out' newline ...
     'if isempty(evm_out)' newline ...
     '    err_acc=double(0); ref_acc=double(1e-10); evm_out=double(-30);' newline ...
     'end' newline ...
     'if valid > 0.5' newline ...
     '    rx_d    = qamdemod(sym, 16, ''UnitAveragePower'', true);' newline ...
     '    ref     = qammod(rx_d, 16, ''UnitAveragePower'', true);' newline ...
     '    err_acc = err_acc + real((sym-ref)*conj(sym-ref));' newline ...
     '    ref_acc = ref_acc + real(ref*conj(ref));' newline ...
     '    evm_out = 10*log10(err_acc / ref_acc);' newline ...
     'end' newline ...
     'evm_db = evm_out;']);

%% ── BER Monitor (패턴 기반 동기) ─────────────────────────────────────────────
% 입력 1: rx_sym   — RX EQ 출력 심볼 (복소)
% 입력 2: rx_valid — 심볼 유효 플래그 (실수)
add_block(lib, [mdl '/BER Monitor'], 'Position',[720 145 880 235]);
set_fcn(mdl, 'BER Monitor', ...
    ['function [ser, ber_est, n_syms, n_correct] = fcn(rx_sym, rx_valid)' newline ...
     '% 패턴 기반 동기: 256심볼 반복 PRNG → 전수 오프셋 탐색 → BER 누산' newline ...
     'persistent rx_buf ref_idx_pat sync_offset' newline ...
     'persistent n_err n_total ser_out ber_out rx_cnt sync_done' newline ...
     'PAT_LEN = int32(256);' newline ...
     'if isempty(rx_buf)' newline ...
     '    %% 참조 패턴 미리 생성 (TX와 동일 PRNG)' newline ...
     '    ref_idx_pat = zeros(PAT_LEN, 1, ''int32'');' newline ...
     '    for k = int32(1):PAT_LEN' newline ...
     '        idx  = double(k - int32(1));' newline ...
     '        seed = mod(idx*20261 + 12345, 65536);' newline ...
     '        b0   = mod(floor(seed),     2);' newline ...
     '        b1   = mod(floor(seed / 2), 2);' newline ...
     '        b2   = mod(floor(seed / 4), 2);' newline ...
     '        b3   = mod(floor(seed / 8), 2);' newline ...
     '        ref_idx_pat(k) = int32(b0 + b1*2 + b2*4 + b3*8);' newline ...
     '    end' newline ...
     '    rx_buf      = complex(zeros(PAT_LEN, 1));' newline ...
     '    sync_offset = int32(0);' newline ...
     '    n_err       = int32(0);  n_total  = int32(0);' newline ...
     '    ser_out     = double(0); ber_out  = double(0);' newline ...
     '    rx_cnt      = int32(0);  sync_done = false;' newline ...
     'end' newline ...
     'ser       = ser_out;' newline ...
     'ber_est   = ber_out;' newline ...
     'n_syms    = double(n_total);' newline ...
     'n_correct = double(n_total - n_err);' newline ...
     'if rx_valid < 0.5, return; end' newline ...
     '%% 순환 버퍼 업데이트' newline ...
     'rx_buf = [rx_sym; rx_buf(1:PAT_LEN-1)];' newline ...
     'rx_cnt = rx_cnt + int32(1);' newline ...
     '%% 256심볼마다 전수 오프셋 탐색' newline ...
     'if mod(rx_cnt, PAT_LEN) == int32(0)' newline ...
     '    %% RX 버퍼 전체 복조 (한 번만)' newline ...
     '    rx_dec = zeros(PAT_LEN, 1, ''int32'');' newline ...
     '    for k = int32(1):PAT_LEN' newline ...
     '        rx_dec(k) = int32(qamdemod(rx_buf(k), 16, ''UnitAveragePower'', true));' newline ...
     '    end' newline ...
     '    %% 오프셋별 오류 수 계산' newline ...
     '    best_off = int32(0);' newline ...
     '    best_err = int32(PAT_LEN + int32(1));' newline ...
     '    for o = int32(0):PAT_LEN-int32(1)' newline ...
     '        e = int32(0);' newline ...
     '        for k = int32(1):PAT_LEN' newline ...
     '            pi_idx = mod(k - int32(1) + o, PAT_LEN) + int32(1);' newline ...
     '            if rx_dec(k) ~= ref_idx_pat(pi_idx)' newline ...
     '                e = e + int32(1);' newline ...
     '            end' newline ...
     '        end' newline ...
     '        if e < best_err' newline ...
     '            best_err = e;' newline ...
     '            best_off = o;' newline ...
     '        end' newline ...
     '    end' newline ...
     '    sync_offset = best_off;' newline ...
     '    sync_done   = true;' newline ...
     'end' newline ...
     '%% 동기 확정 후 BER 누산' newline ...
     'if sync_done' newline ...
     '    pos     = mod(rx_cnt - int32(1) + sync_offset, PAT_LEN) + int32(1);' newline ...
     '    rx_idx  = int32(qamdemod(rx_sym, 16, ''UnitAveragePower'', true));' newline ...
     '    if rx_idx ~= ref_idx_pat(pos)' newline ...
     '        n_err = n_err + int32(1);' newline ...
     '    end' newline ...
     '    n_total = n_total + int32(1);' newline ...
     '    if n_total > int32(0)' newline ...
     '        ser_out = double(n_err) / double(n_total);' newline ...
     '        ber_out = ser_out / 4;' newline ...
     '    end' newline ...
     'end' newline ...
     'ser       = ser_out;' newline ...
     'ber_est   = ber_out;' newline ...
     'n_syms    = double(n_total);' newline ...
     'n_correct = double(n_total - n_err);']);

%% ── Display / Scope ───────────────────────────────────────────────────────────
add_block('simulink/Sinks/Display', [mdl '/EVM (dB)'], ...
    'Position',[940 83 1060 107]);
add_block('simulink/Sinks/Display', [mdl '/SER'], ...
    'Position',[940 150 1060 174]);
add_block('simulink/Sinks/Display', [mdl '/BER est'], ...
    'Position',[940 182 1060 206]);
add_block('simulink/Sinks/Display', [mdl '/N Syms'], ...
    'Position',[940 214 1060 238]);
add_block('simulink/Sinks/Display', [mdl '/N Correct'], ...
    'Position',[940 246 1060 270]);

add_block('simulink/Sinks/Scope', [mdl '/Scope TX'], ...
    'Position',[230 300 280 340]);
add_block('simulink/Sinks/Scope', [mdl '/Scope RX'], ...
    'Position',[660 300 710 340]);

%% ── 연결 ─────────────────────────────────────────────────────────────────────
add_line(mdl, 'TX Model/1',      'Spec1/1');
add_line(mdl, 'Spec1/1',         'Channel Model/1');
add_line(mdl, 'Spec1/1',         'Scope TX/1');
add_line(mdl, 'Channel Model/1', 'Spec2/1');
add_line(mdl, 'Spec2/1',         'RX Model/1');
add_line(mdl, 'RX Model/1',      'EVM Monitor/1');
add_line(mdl, 'RX Model/2',      'EVM Monitor/2');
add_line(mdl, 'EVM Monitor/1',   'EVM (dB)/1');
add_line(mdl, 'RX Model/1',      'Scope RX/1');
add_line(mdl, 'RX Model/1',      'BER Monitor/1');
add_line(mdl, 'RX Model/2',      'BER Monitor/2');
add_line(mdl, 'BER Monitor/1',   'SER/1');
add_line(mdl, 'BER Monitor/2',   'BER est/1');
add_line(mdl, 'BER Monitor/3',   'N Syms/1');
add_line(mdl, 'BER Monitor/4',   'N Correct/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');

save_system(mdl, fullfile(sim_dir, 'full_chain.slx'));
fprintf('Saved: full_chain.slx\n');

function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end
