% build_tx_model.m  [클럭 단위]
% fs = 10 MHz, sps = 4, Rs = 2.5 Mbaud, 16-QAM
% 매 클럭마다 스칼라 복소 샘플 1개 출력

mdl = 'tx_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 200;

%% ── QAM Source ──────────────────────────────────────────────────────────────
% sps 클럭마다 새 16-QAM 심볼 생성, 나머지 클럭은 0 출력 (RRC 업샘플링 준비)
add_block(lib, [mdl '/QAM Source'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'QAM Source', ...
    ['function sym = fcn(dummy)' newline ...
     '% 16-QAM 심볼 생성 — sps=4 클럭마다 새 심볼' newline ...
     'persistent cnt buf_sym' newline ...
     'if isempty(cnt), cnt = int32(0); buf_sym = complex(0,0); end' newline ...
     'SPS = int32(4);' newline ...
     'if cnt == int32(0)' newline ...
     '    bits    = randi([0 1], 4, 1);' newline ...
     '    buf_sym = qammod(bits, 16, ''InputType'',''bit'',''UnitAveragePower'',true);' newline ...
     'end' newline ...
     'if cnt == int32(0)' newline ...
     '    sym = buf_sym;' newline ...
     'else' newline ...
     '    sym = complex(0, 0);' newline ...
     'end' newline ...
     'cnt = mod(cnt + int32(1), SPS);']);
set_cplx(mdl, 'QAM Source', 'sym');
px = px + step;

%% ── RRC FIR Filter (업샘플 포함) ────────────────────────────────────────────
% 33탭 RRC 지연선 — persistent 레지스터로 클럭마다 1샘플 처리
add_block(lib, [mdl '/RRC FIR'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'RRC FIR', ...
    ['function y = fcn(x)' newline ...
     '% 33-tap RRC FIR  (span=8, sps=4, rolloff=0.25)' newline ...
     'persistent dl h' newline ...
     'NTAP = int32(33);' newline ...
     'if isempty(dl)' newline ...
     '    h  = rcosdesign(0.25, 8, 4, ''sqrt'');' newline ...
     '    dl = complex(zeros(NTAP, 1));' newline ...
     'end' newline ...
     'dl = [x; dl(1:NTAP-1)];' newline ...
     'y  = complex(h * dl);']);
set_cplx(mdl, 'RRC FIR', 'y');
px = px + step;

%% ── RF Impairments ───────────────────────────────────────────────────────────
% IQ 불균형(진폭+위상), 위상잡음, DC 오프셋 — 클럭마다 스칼라 처리
add_block(lib, [mdl '/RF Impairments'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'RF Impairments', ...
    ['function y = fcn(x)' newline ...
     '% IQ 불균형 + 위상잡음 + DC 오프셋' newline ...
     'persistent phase_noise_acc' newline ...
     'if isempty(phase_noise_acc), phase_noise_acc = double(0); end' newline ...
     'amp = 10^(0.5/20);' newline ...
     'ph  = 1 * pi / 180;' newline ...
     'I   = real(x); Q = imag(x);' newline ...
     'iq  = complex(amp*(I*cos(ph/2) - Q*sin(ph/2)), ...' newline ...
     '              I*sin(ph/2) + Q*cos(ph/2));' newline ...
     'phase_noise_acc = phase_noise_acc + sqrt(1e-6) * randn;' newline ...
     'y = iq * exp(complex(0, phase_noise_acc)) + complex(0.005, 0.005);']);
set_cplx(mdl, 'RF Impairments', 'y');
px = px + step;

%% ── Output ───────────────────────────────────────────────────────────────────
add_block('simulink/Sinks/Out1', [mdl '/TX Out'], ...
    'Position',[px 70 px+30 90], ...
    'PortDimensions','1', 'SignalType','complex');

%% ── 트리거 상수 (QAM Source dummy 입력) ─────────────────────────────────────
add_block('simulink/Sources/Constant', [mdl '/Trigger'], ...
    'Value','0', 'SampleTime','1/10e6', 'Position',[30 155 100 185]);

%% ── 연결 ─────────────────────────────────────────────────────────────────────
add_line(mdl, 'Trigger/1',       'QAM Source/1');
add_line(mdl, 'QAM Source/1',    'RRC FIR/1');
add_line(mdl, 'RRC FIR/1',       'RF Impairments/1');
add_line(mdl, 'RF Impairments/1','TX Out/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'tx_model.slx'));
fprintf('Saved: tx_model.slx\n');

%% ── 헬퍼 ─────────────────────────────────────────────────────────────────────
function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end

function set_cplx(mdl, blk, port_name)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    d  = ch.find('-isa','Stateflow.Data','Name', port_name);
    if ~isempty(d), d(1).Complexity = 'On'; end
end
