% build_rx_model.m
% RX: AGC → FreqSync → PhaseSync → ChEst → MMSE EQ
% Timing Sync / FEC는 크기 변환이 필요해 Simulink 레벨에서 제외
% (MATLAB 스크립트 시뮬레이션에서 처리)
% 모든 블록 입출력 크기 동일 (복소 심볼 벡터)

mdl = 'rx_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 210;

%% Input
add_block('simulink/Sources/In1', [mdl '/RX In'], 'Position',[px 70 px+30 90]);
px = px + step;

%% AGC
add_block(lib, [mdl '/AGC'], 'Position',[px 55 px+130 105]);
set_fcn(mdl, 'AGC', ...
    ['function y = fcn(x)' newline ...
     'g = sqrt(1 / (mean(abs(x).^2) + eps));' newline ...
     'y = x * g;']);
set_complex_output(mdl, 'AGC');
px = px + step;

%% Freq Sync (FFT-based coarse Doppler estimation)
add_block(lib, [mdl '/Freq Sync'], 'Position',[px 55 px+130 105]);
set_fcn(mdl, 'Freq Sync', ...
    ['function y = fcn(x)' newline ...
     'N  = numel(x);' newline ...
     '[~, idx] = max(abs(fft(x .^ 4, N)));' newline ...
     'fo = (double(idx) - 1) * 10e6 / double(N) / 4;' newline ...
     'if fo > 10e6/2, fo = fo - 10e6; end' newline ...
     't  = (0:N-1)'' / 10e6;' newline ...
     'y  = x .* exp(complex(0, -2*pi*fo*t));']);
set_complex_output(mdl, 'Freq Sync');
px = px + step;

%% Phase Sync (Costas loop)
add_block(lib, [mdl '/Phase Sync'], 'Position',[px 55 px+130 105]);
set_fcn(mdl, 'Phase Sync', ...
    ['function y = fcn(x)' newline ...
     'persistent ph fr' newline ...
     'if isempty(ph), ph = double(0); fr = double(0); end' newline ...
     'alpha = 0.05;' newline ...
     'n     = numel(x);' newline ...
     'y     = complex(zeros(n,1));' newline ...
     'for k = 1:n' newline ...
     '    y(k) = x(k) * exp(complex(0,-ph));' newline ...
     '    d    = complex(sign(real(y(k))), sign(imag(y(k))));' newline ...
     '    e    = imag(y(k) * conj(d));' newline ...
     '    fr   = fr + 0.0025*e;' newline ...
     '    ph   = ph + alpha*e + fr;' newline ...
     'end']);
set_complex_output(mdl, 'Phase Sync');
px = px + step;

%% Channel Estimator (LS — pass through with unity gain assumption)
add_block(lib, [mdl '/Ch Estimator'], 'Position',[px 55 px+130 105]);
set_fcn(mdl, 'Ch Estimator', ...
    ['function [y, H] = fcn(x)' newline ...
     '% Simple LS: assume pilot = 1+0j every 8th symbol' newline ...
     'N = numel(x);' newline ...
     'pilot_idx = int32(8:8:N);' newline ...
     'H_pilot   = x(pilot_idx);   % pilot value known = 1+0j' newline ...
     'H = complex(ones(N,1));' newline ...
     'for i = 1:numel(pilot_idx)-1' newline ...
     '    H(pilot_idx(i):pilot_idx(i+1)) = H_pilot(i);' newline ...
     'end' newline ...
     'y = x;']);
set_complex_output(mdl, 'Ch Estimator');
px = px + step;

%% MMSE Equalizer
add_block(lib, [mdl '/MMSE EQ'], 'Position',[px 55 px+130 105]);
set_fcn(mdl, 'MMSE EQ', ...
    ['function y = fcn(x, H)' newline ...
     'nv = 0.01;' newline ...
     'y  = conj(H) ./ (abs(H).^2 + nv) .* x;']);
set_complex_output(mdl, 'MMSE EQ');
px = px + step;

%% Output (복소 등화 심볼)
add_block('simulink/Sinks/Out1', [mdl '/EQ Symbols'], 'Position',[px 70 px+30 90]);

%% Connections
add_line(mdl, 'RX In/1',       'AGC/1');
add_line(mdl, 'AGC/1',         'Freq Sync/1');
add_line(mdl, 'Freq Sync/1',   'Phase Sync/1');
add_line(mdl, 'Phase Sync/1',  'Ch Estimator/1');
add_line(mdl, 'Ch Estimator/1','MMSE EQ/1');
add_line(mdl, 'Ch Estimator/2','MMSE EQ/2');
add_line(mdl, 'MMSE EQ/1',     'EQ Symbols/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1','StopTime','100');

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'rx_model.slx'));
fprintf('Saved: rx_model.slx\n');

%% Helpers
function set_fcn(mdl, blk_name, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk_name]);
    ch.Script = script;
end

function set_complex_output(mdl, blk_name)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk_name]);
    dlist = ch.find('-isa','Stateflow.Data','Name','y');
    for i = 1:numel(dlist)
        dlist(i).Complexity = 'On';
    end
end
