% build_channel_model.m — Programmatically creates channel_model.slx
% All channel effects implemented as MATLAB Function blocks (no toolbox dependency)

mdl = 'channel_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 200;

%% Input
add_block('simulink/Sources/In1', [mdl '/TX In'], 'Position',[px 70 px+30 90]);
px = px + step;

%% Multipath Rayleigh (ITU VehA — implemented via MATLAB Function)
add_block(lib, [mdl '/Multipath'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Multipath', ...
    ['function y = fcn(x)' newline ...
     '% ITU Vehicular-A 6-tap Rayleigh fading' newline ...
     '% Tap delays in samples @10MHz: [0 3 7 10 17 25]' newline ...
     'tap_d  = int32([0 3 7 10 17 25]);' newline ...
     'gains  = 10.^([0 -1 -9 -10 -15 -20]/20);' newline ...
     'MAX_D  = int32(25);' newline ...
     'persistent buf' newline ...
     'if isempty(buf), buf = complex(zeros(MAX_D+1, 1)); end' newline ...
     'n = numel(x);' newline ...
     'y = complex(zeros(n, 1));' newline ...
     'for i = 1:n' newline ...
     '    buf = [x(i); buf(1:MAX_D)];' newline ...
     '    s   = complex(0);' newline ...
     '    for k = 1:6' newline ...
     '        h = (randn + 1j*randn)/sqrt(2);' newline ...
     '        s = s + gains(k) * h * buf(tap_d(k)+1);' newline ...
     '    end' newline ...
     '    y(i) = s;' newline ...
     'end']);
px = px + step;

%% Doppler Shift
add_block(lib, [mdl '/Doppler'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Doppler', ...
    ['function y = fcn(x)' newline ...
     '% Doppler shift 5 kHz — time relative to frame start (phase continuity via persistent)' newline ...
     'persistent phase' newline ...
     'if isempty(phase), phase = 0; end' newline ...
     'fs = 10e6; fo = 5000;' newline ...
     'n  = numel(x);' newline ...
     'y  = zeros(n, 1);' newline ...
     'for k = 1:n' newline ...
     '    y(k) = x(k) * exp(1j * phase);' newline ...
     '    phase = phase + 2*pi*fo/fs;' newline ...
     'end']);
px = px + step;

%% AWGN
add_block(lib, [mdl '/AWGN'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'AWGN', ...
    ['function y = fcn(x, EbNo_dB)' newline ...
     '% Add AWGN given Eb/N0 (dB), BPS=4 (16-QAM)' newline ...
     'bps      = 4;' newline ...
     'EsNo     = EbNo_dB + 10*log10(bps);' newline ...
     'sig_pwr  = mean(abs(x).^2);' newline ...
     'noise_var = sig_pwr / (10^(EsNo/10));' newline ...
     'n = sqrt(noise_var/2) * (randn(size(x)) + 1j*randn(size(x)));' newline ...
     'y = x + n;']);
px = px + step;

%% Constant for EbNo input
add_block('simulink/Sources/Constant', [mdl '/EbNo'], ...
    'Value','10', 'SampleTime','inf', ...
    'Position',[px-step 155 px-step+80 185]);

%% Output
add_block('simulink/Sinks/Out1', [mdl '/RX Out'], 'Position',[px 70 px+30 90]);

%% Connections
add_line(mdl, 'TX In/1',    'Multipath/1');
add_line(mdl, 'Multipath/1','Doppler/1');
add_line(mdl, 'Doppler/1',  'AWGN/1');
add_line(mdl, 'EbNo/1',     'AWGN/2');
add_line(mdl, 'AWGN/1',     'RX Out/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'channel_model.slx'));
fprintf('Saved: channel_model.slx\n');

function set_fcn(mdl, blk_name, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk_name]);
    ch.Script = script;
end
