% build_channel_model.m  [클럭 단위]
% 매 클럭(1/10MHz)마다 스칼라 복소 샘플 처리
% Multipath → Doppler → AWGN

mdl = 'channel_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 200;

%% ── Input ────────────────────────────────────────────────────────────────────
add_block('simulink/Sources/In1', [mdl '/TX In'], ...
    'Position',[px 70 px+30 90], ...
    'PortDimensions','1', 'SignalType','complex');
px = px + step;

%% ── Multipath (ITU VehA 6탭 시프트 레지스터) ────────────────────────────────
% 탭 지연 @10MHz: [0 3 7 10 17 25] 샘플
add_block(lib, [mdl '/Multipath'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Multipath', ...
    ['function y = fcn(x)' newline ...
     '% 26-샘플 시프트 레지스터 — ITU VehA 6-tap Rayleigh' newline ...
     'TAP_D = int32([0 3 7 10 17 25]);' newline ...
     'GAINS = 10.^([0 -1 -9 -10 -15 -20]/20);' newline ...
     'LEN   = int32(26);' newline ...
     'persistent sr' newline ...
     'if isempty(sr), sr = complex(zeros(LEN, 1)); end' newline ...
     'sr = [x; sr(1:LEN-1)];' newline ...
     's  = complex(0, 0);' newline ...
     'for k = 1:6' newline ...
     '    h = complex(randn,randn)/sqrt(2);' newline ...
     '    s = s + GAINS(k) * h * sr(TAP_D(k)+1);' newline ...
     'end' newline ...
     'y = s;']);
set_cplx(mdl, 'Multipath', 'y');
px = px + step;

%% ── Doppler (위상 누적기 — 클럭마다 갱신) ───────────────────────────────────
add_block(lib, [mdl '/Doppler'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Doppler', ...
    ['function y = fcn(x)' newline ...
     '% 위상 누적기: fo=5000 Hz, fs=10 MHz' newline ...
     'persistent phase' newline ...
     'if isempty(phase), phase = double(0); end' newline ...
     'y     = x * exp(complex(0, phase));' newline ...
     'phase = phase + 2*pi*5000/10e6;' newline ...
     'if phase > pi, phase = phase - 2*pi; end']);
set_cplx(mdl, 'Doppler', 'y');
px = px + step;

%% ── AWGN (클럭마다 스칼라 잡음 추가) ────────────────────────────────────────
add_block(lib, [mdl '/AWGN'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'AWGN', ...
    ['function y = fcn(x, EbNo_dB)' newline ...
     '% Eb/N0 기반 AWGN — BPS=4 (16-QAM), sps=4' newline ...
     'bps     = 4;' newline ...
     'EsNo    = EbNo_dB + 10*log10(double(bps));' newline ...
     'nv      = 1 / (10^(EsNo/10));' newline ...
     'noise   = complex(randn, randn) * sqrt(nv/2);' newline ...
     'y       = x + noise;']);
set_cplx(mdl, 'AWGN', 'y');
px = px + step;

%% ── EbNo 상수 입력 ───────────────────────────────────────────────────────────
add_block('simulink/Sources/Constant', [mdl '/EbNo'], ...
    'Value','10', 'SampleTime','inf', ...
    'Position',[px-step 160 px-step+80 190]);

%% ── Output ───────────────────────────────────────────────────────────────────
add_block('simulink/Sinks/Out1', [mdl '/RX Out'], ...
    'Position',[px 70 px+30 90], ...
    'PortDimensions','1', 'SignalType','complex');

%% ── 연결 ─────────────────────────────────────────────────────────────────────
add_line(mdl, 'TX In/1',    'Multipath/1');
add_line(mdl, 'Multipath/1','Doppler/1');
add_line(mdl, 'Doppler/1',  'AWGN/1');
add_line(mdl, 'EbNo/1',     'AWGN/2');
add_line(mdl, 'AWGN/1',     'RX Out/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'channel_model.slx'));
fprintf('Saved: channel_model.slx\n');

function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end

function set_cplx(mdl, blk, port_name)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    d  = ch.find('-isa','Stateflow.Data','Name', port_name);
    if ~isempty(d), d(1).Complexity = 'On'; end
end
