% build_tx_model.m  [클럭 단위]
% 256심볼 반복 결정론적 PRNG 패턴 → 16-QAM → RRC → RF불균형
%
% 패턴: seed = mod(sym_idx * 20261 + 12345, 65536)  (idx=0..255 반복)
% 출력 1: TX 신호 (복소)

mdl = 'tx_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 200;

%% ── QAM Source (256심볼 반복 PRNG) ──────────────────────────────────────────
add_block(lib, [mdl '/QAM Source'], 'Position',[px 40 px+140 110]);
set_fcn(mdl, 'QAM Source', ...
    ['function sym = fcn(dummy)' newline ...
     '% 256-symbol repeating PRNG 16-QAM pattern' newline ...
     'persistent sym_cnt sps_cnt cur_sym' newline ...
     'PAT_LEN = int32(256);' newline ...
     'SPS     = int32(4);' newline ...
     'if isempty(sym_cnt)' newline ...
     '    sym_cnt = int32(0); sps_cnt = int32(0);' newline ...
     '    cur_sym = complex(1, 0);' newline ...
     'end' newline ...
     'if sps_cnt == int32(0)' newline ...
     '    idx  = double(sym_cnt);' newline ...
     '    seed = mod(idx*20261 + 12345, 65536);' newline ...
     '    b0   = mod(floor(seed),     2);' newline ...
     '    b1   = mod(floor(seed / 2), 2);' newline ...
     '    b2   = mod(floor(seed / 4), 2);' newline ...
     '    b3   = mod(floor(seed / 8), 2);' newline ...
     '    cur_sym = qammod([b0;b1;b2;b3], 16, ''InputType'',''bit'',''UnitAveragePower'',true);' newline ...
     '    sym_cnt = mod(sym_cnt + int32(1), PAT_LEN);' newline ...
     'end' newline ...
     'sym     = cur_sym;' newline ...
     'sps_cnt = mod(sps_cnt + int32(1), SPS);']);
set_cplx(mdl, 'QAM Source', 'sym');
px = px + step;

%% ── RRC FIR Filter ───────────────────────────────────────────────────────────
add_block(lib, [mdl '/RRC FIR'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'RRC FIR', ...
    ['function y = fcn(x)' newline ...
     'persistent dl h' newline ...
     'NTAP = int32(33);' newline ...
     'if isempty(dl)' newline ...
     '    h  = rcosdesign(0.25, 8, 4, ''sqrt'');' newline ...
     '    dl = complex(zeros(NTAP, 1));' newline ...
     'end' newline ...
     'dl = [x; dl(1:NTAP-1)];' newline ...
     'y  = complex(h * dl);']);
set_cplx(mdl, 'RRC FIR', 'y');
px = px + step;

%% ── RF Impairments ───────────────────────────────────────────────────────────
add_block(lib, [mdl '/RF Impairments'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'RF Impairments', ...
    ['function y = fcn(x)' newline ...
     'persistent pn_acc' newline ...
     'if isempty(pn_acc), pn_acc = double(0); end' newline ...
     'amp = 10^(0.5/20); ph = 1*pi/180;' newline ...
     'I = real(x); Q = imag(x);' newline ...
     'iq = complex(amp*(I*cos(ph/2)-Q*sin(ph/2)), I*sin(ph/2)+Q*cos(ph/2));' newline ...
     'pn_acc = pn_acc + sqrt(1e-6)*randn;' newline ...
     'y = iq * exp(complex(0,pn_acc)) + complex(0.005,0.005);']);
set_cplx(mdl, 'RF Impairments', 'y');
px = px + step;

%% ── Output ───────────────────────────────────────────────────────────────────
add_block('simulink/Sinks/Out1', [mdl '/TX Out'], ...
    'Position',[px 65 px+30 85], 'PortDimensions','1','SignalType','complex');

%% ── 트리거 ───────────────────────────────────────────────────────────────────
add_block('simulink/Sources/Constant', [mdl '/Trigger'], ...
    'Value','0','SampleTime','1/10e6','Position',[30 180 100 210]);

%% ── 연결 ─────────────────────────────────────────────────────────────────────
add_line(mdl, 'Trigger/1',        'QAM Source/1');
add_line(mdl, 'QAM Source/1',     'RRC FIR/1');
add_line(mdl, 'RRC FIR/1',        'RF Impairments/1');
add_line(mdl, 'RF Impairments/1', 'TX Out/1');

set_param(mdl,'SolverType','Fixed-step','Solver','FixedStepDiscrete',...
    'FixedStep','1/10e6','StopTime','1e-3');
save_system(mdl, fullfile(fileparts(mfilename('fullpath')),'tx_model.slx'));
fprintf('Saved: tx_model.slx\n');

function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end
function set_cplx(mdl, blk, port_name)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    d  = ch.find('-isa','Stateflow.Data','Name', port_name);
    if ~isempty(d), d(1).Complexity = 'On'; end
end
