% build_full_chain.m  [클럭 단위]
% TX → Channel → RX 통합 모델 + BER/EVM 측정
%
% 파이프라인 지연 보상 (PIPE_DELAY = 36 클럭):
%   TX RRC FIR 군지연  16 클럭
%   RX RRC MF  군지연  16 클럭
%   Timing Sync 지연    4 클럭
%   합계               36 클럭

mdl     = 'full_chain';
sim_dir = fileparts(mfilename('fullpath'));

if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib        = 'simulink/User-Defined Functions/MATLAB Function';
PIPE_DELAY = 36;   % 클럭 단위 파이프라인 지연

%% ── Sub-models (Model Reference) ─────────────────────────────────────────────
add_block('simulink/Ports & Subsystems/Model', [mdl '/TX Model'], ...
    'ModelName','tx_model','Position',[60 80 200 170]);

add_block('simulink/Ports & Subsystems/Model', [mdl '/Channel Model'], ...
    'ModelName','channel_model','Position',[280 90 420 140]);

add_block('simulink/Ports & Subsystems/Model', [mdl '/RX Model'], ...
    'ModelName','rx_model','Position',[500 80 640 150]);

%% ── Signal Specification (스칼라 복소 명시) ──────────────────────────────────
add_block('simulink/Signal Attributes/Signal Specification', [mdl '/Spec1'], ...
    'Dimensions','1', 'Position',[230 103 260 127]);

add_block('simulink/Signal Attributes/Signal Specification', [mdl '/Spec2'], ...
    'Dimensions','1', 'Position',[450 103 480 127]);

%% ── 파이프라인 지연 보상 (TX 기준 심볼 & Valid) ──────────────────────────────
% TX Model 출력 2: TX 기준 심볼 (복소)
% TX Model 출력 3: TX Valid (실수)
add_block('simulink/Discrete/Delay', [mdl '/TX Ref Delay'], ...
    'DelayLength', num2str(PIPE_DELAY), ...
    'InitialCondition', '0', ...
    'Position',[280 200 390 230]);

add_block('simulink/Discrete/Delay', [mdl '/TX Valid Delay'], ...
    'DelayLength', num2str(PIPE_DELAY), ...
    'InitialCondition', '0', ...
    'Position',[280 250 390 280]);

%% ── EVM 모니터 ────────────────────────────────────────────────────────────────
add_block(lib, [mdl '/EVM Monitor'], 'Position',[720 75 880 125]);
set_fcn(mdl, 'EVM Monitor', ...
    ['function evm_db = fcn(sym, valid)' newline ...
     '% 복소 심볼 EVM 추정 — valid=1인 샘플만 사용' newline ...
     'persistent err_acc ref_acc n' newline ...
     'if isempty(n), err_acc=double(0); ref_acc=double(1e-10); n=int32(0); end' newline ...
     'evm_db = double(-30);' newline ...
     'if valid > 0.5' newline ...
     '    rx_d    = qamdemod(sym, 16, ''UnitAveragePower'', true);' newline ...
     '    ref     = qammod(rx_d, 16, ''UnitAveragePower'', true);' newline ...
     '    err_acc = err_acc + real((sym-ref)*conj(sym-ref));' newline ...
     '    ref_acc = ref_acc + real(ref*conj(ref));' newline ...
     '    n = n + int32(1);' newline ...
     '    if n >= int32(100)' newline ...
     '        evm_db = 10*log10(err_acc / ref_acc);' newline ...
     '    end' newline ...
     'end']);

%% ── BER 모니터 ────────────────────────────────────────────────────────────────
% 입력: rx_sym, rx_valid, tx_ref(지연 보상된 기준 심볼), tx_valid(지연 보상됨)
% 출력: ser (심볼 오율), n_syms (누적 심볼 수), ber_est (BER 추정 = SER/4)
add_block(lib, [mdl '/BER Monitor'], 'Position',[720 155 880 235]);
set_fcn(mdl, 'BER Monitor', ...
    ['function [ser, ber_est, n_syms] = fcn(rx_sym, rx_valid, tx_ref, tx_valid)' newline ...
     '% 16-QAM BER 측정 — 파이프라인 지연 보상된 TX 기준 심볼과 비교' newline ...
     'persistent n_err n_total' newline ...
     'if isempty(n_err), n_err = int32(0); n_total = int32(0); end' newline ...
     'ser     = double(0);' newline ...
     'ber_est = double(0);' newline ...
     'n_syms  = double(n_total);' newline ...
     'if rx_valid > 0.5 && tx_valid > 0.5' newline ...
     '    rx_idx = qamdemod(rx_sym, 16, ''UnitAveragePower'', true);' newline ...
     '    tx_idx = qamdemod(tx_ref, 16, ''UnitAveragePower'', true);' newline ...
     '    if rx_idx ~= tx_idx' newline ...
     '        n_err = n_err + int32(1);' newline ...
     '    end' newline ...
     '    n_total = n_total + int32(1);' newline ...
     '    if n_total >= int32(20)' newline ...
     '        ser     = double(n_err) / double(n_total);' newline ...
     '        ber_est = ser / 4;   % 16-QAM Gray 부호 근사: BER≈SER/log2(16)' newline ...
     '    end' newline ...
     '    n_syms = double(n_total);' newline ...
     'end']);

%% ── Display / Scope ───────────────────────────────────────────────────────────
add_block('simulink/Sinks/Display', [mdl '/EVM (dB)'], ...
    'Position',[940 83 1060 107]);

add_block('simulink/Sinks/Display', [mdl '/SER'], ...
    'Position',[940 158 1060 182]);

add_block('simulink/Sinks/Display', [mdl '/BER est'], ...
    'Position',[940 190 1060 214]);

add_block('simulink/Sinks/Display', [mdl '/N Syms'], ...
    'Position',[940 222 1060 246]);

add_block('simulink/Sinks/Scope', [mdl '/Scope TX'], ...
    'Position',[230 310 280 350]);

add_block('simulink/Sinks/Scope', [mdl '/Scope RX'], ...
    'Position',[660 310 710 350]);

%% ── 연결: 메인 신호 체인 ─────────────────────────────────────────────────────
add_line(mdl, 'TX Model/1',      'Spec1/1');
add_line(mdl, 'Spec1/1',         'Channel Model/1');
add_line(mdl, 'Spec1/1',         'Scope TX/1');
add_line(mdl, 'Channel Model/1', 'Spec2/1');
add_line(mdl, 'Spec2/1',         'RX Model/1');
add_line(mdl, 'RX Model/1',      'EVM Monitor/1');   % EQ 심볼
add_line(mdl, 'RX Model/2',      'EVM Monitor/2');   % valid
add_line(mdl, 'RX Model/1',      'Scope RX/1');
add_line(mdl, 'EVM Monitor/1',   'EVM (dB)/1');

%% ── 연결: BER 경로 (지연 보상) ───────────────────────────────────────────────
add_line(mdl, 'TX Model/2',         'TX Ref Delay/1');    % TX 기준 심볼
add_line(mdl, 'TX Model/3',         'TX Valid Delay/1');  % TX valid
add_line(mdl, 'RX Model/1',         'BER Monitor/1');     % RX EQ 심볼
add_line(mdl, 'RX Model/2',         'BER Monitor/2');     % RX valid
add_line(mdl, 'TX Ref Delay/1',     'BER Monitor/3');     % 지연 보상된 TX 기준
add_line(mdl, 'TX Valid Delay/1',   'BER Monitor/4');     % 지연 보상된 TX valid
add_line(mdl, 'BER Monitor/1',      'SER/1');
add_line(mdl, 'BER Monitor/2',      'BER est/1');
add_line(mdl, 'BER Monitor/3',      'N Syms/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');

save_system(mdl, fullfile(sim_dir, 'full_chain.slx'));
fprintf('Saved: full_chain.slx\n');
fprintf('파이프라인 지연 보상: %d 클럭 (%.1f µs)\n', PIPE_DELAY, PIPE_DELAY/10);

function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end
