% build_rx_model.m  [클럭 단위]
% AGC → RRC MF → Freq Sync → Timing Sync → Phase Sync → Ch Est → MMSE EQ → Frame Sync
%
% Frame Sync:
%   - Preamble 검출: 16심볼 슬라이딩 상관 (복소 → 위상 무관)
%   - 프리앰블 상관 피크에서 위상 오차 추정 → ph_corr로 이후 심볼 보정
%   - Header 복조: nibble×4(frame_cnt) + CRC-4 검증
%   - Data 출력: 256심볼, data_valid=1
%
% 출력 1: data_sym     — 데이터 구간 심볼 (복소)
% 출력 2: data_valid   — 데이터 유효 플래그 (실수)
% 출력 3: rx_frame_cnt — 헤더에서 복조한 프레임 번호 (실수)

mdl = 'rx_model';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);
open_system(mdl);

lib  = 'simulink/User-Defined Functions/MATLAB Function';
px   = 30; step = 200;

%% ── Input ────────────────────────────────────────────────────────────────────
add_block('simulink/Sources/In1', [mdl '/RX In'], ...
    'Position',[px 70 px+30 90], ...
    'PortDimensions','1', 'SignalType','complex');
px = px + step;

%% ── AGC ──────────────────────────────────────────────────────────────────────
add_block(lib, [mdl '/AGC'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'AGC', ...
    ['function y = fcn(x)' newline ...
     'persistent pwr_est' newline ...
     'if isempty(pwr_est), pwr_est = double(1); end' newline ...
     'alpha   = 0.001;' newline ...
     'pwr_est = (1-alpha)*pwr_est + alpha*real(x*conj(x));' newline ...
     'g       = 1 / sqrt(pwr_est + 1e-10);' newline ...
     'y       = x * g;']);
set_cplx(mdl, 'AGC', 'y');
px = px + step;

%% ── RRC Matched Filter ───────────────────────────────────────────────────────
add_block(lib, [mdl '/RRC MF'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'RRC MF', ...
    ['function y = fcn(x)' newline ...
     'persistent dl h' newline ...
     'NTAP = int32(33);' newline ...
     'if isempty(dl)' newline ...
     '    h  = rcosdesign(0.25, 8, 4, ''sqrt'');' newline ...
     '    dl = complex(zeros(NTAP, 1));' newline ...
     'end' newline ...
     'dl = [x; dl(1:NTAP-1)];' newline ...
     'y  = complex(h * dl);']);
set_cplx(mdl, 'RRC MF', 'y');
px = px + step;

%% ── Freq Sync (DD-PLL) ───────────────────────────────────────────────────────
add_block(lib, [mdl '/Freq Sync'], 'Position',[px 55 px+140 105]);
set_fcn(mdl, 'Freq Sync', ...
    ['function y = fcn(x)' newline ...
     'persistent phase freq' newline ...
     'if isempty(phase), phase = double(0); freq = double(0); end' newline ...
     'K1 = 0.001; K2 = 1e-6;' newline ...
     'y  = x * exp(complex(0,-phase));' newline ...
     'd  = complex(sign(real(y)), sign(imag(y)));' newline ...
     'e  = imag(y * conj(d));' newline ...
     'freq  = freq  + K2*e;' newline ...
     'phase = phase + K1*e + freq;' newline ...
     'if phase >  pi, phase = phase - 2*pi; end' newline ...
     'if phase < -pi, phase = phase + 2*pi; end']);
set_cplx(mdl, 'Freq Sync', 'y');
px = px + step;

%% ── Timing Sync (Gardner TED) ────────────────────────────────────────────────
add_block(lib, [mdl '/Timing Sync'], 'Position',[px 55 px+140 125]);
set_fcn(mdl, 'Timing Sync', ...
    ['function [sym, valid] = fcn(x)' newline ...
     'persistent mu cnt prev mid' newline ...
     'SPS = double(4);' newline ...
     'if isempty(mu)' newline ...
     '    mu   = double(0); cnt  = double(0);' newline ...
     '    prev = complex(0,0); mid = complex(0,0);' newline ...
     'end' newline ...
     'sym   = complex(0, 0);' newline ...
     'valid = double(0);' newline ...
     'cnt = cnt + 1;' newline ...
     'if cnt == floor(SPS/2)' newline ...
     '    mid = x;' newline ...
     'end' newline ...
     'if cnt >= SPS' newline ...
     '    ted   = real(mid)*(real(prev)-real(x)) + imag(mid)*(imag(prev)-imag(x));' newline ...
     '    mu    = mu + 0.01*ted;' newline ...
     '    mu    = max(-0.5, min(0.5, mu));' newline ...
     '    sym   = x + mu*(x-prev);' newline ...
     '    valid = double(1);' newline ...
     '    prev  = x;' newline ...
     '    cnt   = double(0);' newline ...
     'end']);
set_cplx(mdl, 'Timing Sync', 'sym');
px = px + step;

%% ── Phase Sync (Costas Loop) ─────────────────────────────────────────────────
add_block(lib, [mdl '/Phase Sync'], 'Position',[px 55 px+140 125]);
set_fcn(mdl, 'Phase Sync', ...
    ['function y = fcn(x, valid)' newline ...
     'persistent ph fr' newline ...
     'if isempty(ph), ph = double(0); fr = double(0); end' newline ...
     'y = x * exp(complex(0,-ph));' newline ...
     'if valid > 0.5' newline ...
     '    d  = complex(sign(real(y)), sign(imag(y)));' newline ...
     '    e  = imag(y * conj(d));' newline ...
     '    fr = fr + 0.005*e;' newline ...
     '    ph = ph + 0.05*e + fr;' newline ...
     'end']);
set_cplx(mdl, 'Phase Sync', 'y');
px = px + step;

%% ── Channel Estimator ────────────────────────────────────────────────────────
add_block(lib, [mdl '/Ch Est'], 'Position',[px 55 px+140 125]);
set_fcn(mdl, 'Ch Est', ...
    ['function [y, H] = fcn(x, valid)' newline ...
     'persistent sym_cnt H_est' newline ...
     'PILOT_PERIOD = int32(8);' newline ...
     'if isempty(sym_cnt), sym_cnt = int32(0); H_est = complex(1,0); end' newline ...
     'H = H_est;' newline ...
     'y = x;' newline ...
     'if valid > 0.5' newline ...
     '    sym_cnt = sym_cnt + int32(1);' newline ...
     '    if mod(sym_cnt, PILOT_PERIOD) == int32(0)' newline ...
     '        H_est = complex(0.9,0)*H_est + complex(0.1,0)*x;' newline ...
     '    end' newline ...
     'end']);
set_cplx(mdl, 'Ch Est', 'y');
set_cplx(mdl, 'Ch Est', 'H');
px = px + step;

%% ── MMSE Equalizer ───────────────────────────────────────────────────────────
add_block(lib, [mdl '/MMSE EQ'], 'Position',[px 55 px+140 125]);
set_fcn(mdl, 'MMSE EQ', ...
    ['function y = fcn(x, H)' newline ...
     'nv = 0.01;' newline ...
     'y  = conj(H) / (real(H*conj(H)) + nv) * x;']);
set_cplx(mdl, 'MMSE EQ', 'y');
px = px + step;

%% ── Frame Sync ───────────────────────────────────────────────────────────────
% Preamble: [+1,-1,+1,-1,...] × 16  (BPSK)
% Header:   nibble×4(frame_cnt 16bit) + CRC-4 nibble  (5심볼, 16-QAM)
% Data:     256심볼 16-QAM
%
% 프리앰블 복소 상관으로 위상 모호성까지 해결:
%   ph_corr = conj(corr_val) / |corr_val|   (단위 페이저)
%   이후 모든 심볼에 ph_corr 곱해서 위상 정렬
add_block(lib, [mdl '/Frame Sync'], 'Position',[px 50 px+140 175]);
set_fcn(mdl, 'Frame Sync', ...
    ['function [data_sym, data_valid, rx_frame_cnt] = fcn(sym, valid)' newline ...
     'persistent sym_buf fs_state sym_idx frame_cnt_rx crc_ok header_nibs ph_corr' newline ...
     'N_PREAM = int32(16);' newline ...
     'N_HEAD  = int32(5);' newline ...
     'N_DATA  = int32(256);' newline ...
     'CORR_TH = double(8.0);' newline ...
     'if isempty(sym_buf)' newline ...
     '    sym_buf      = complex(zeros(N_PREAM, 1));' newline ...
     '    fs_state     = int32(0);' newline ...
     '    sym_idx      = int32(0);' newline ...
     '    frame_cnt_rx = double(0);' newline ...
     '    crc_ok       = false;' newline ...
     '    header_nibs  = zeros(4, 1);' newline ...
     '    ph_corr      = complex(1, 0);' newline ...
     'end' newline ...
     'data_sym     = complex(0, 0);' newline ...
     'data_valid   = double(0);' newline ...
     'rx_frame_cnt = frame_cnt_rx;' newline ...
     'if valid < 0.5, return; end' newline ...
     '%% 슬라이딩 버퍼' newline ...
     'sym_buf = [sym; sym_buf(1:N_PREAM-1)];' newline ...
     'if fs_state == int32(0)' newline ...
     '    %% SEARCH: 복소 상관 (위상 무관 검출 + 위상 추정)' newline ...
     '    ref = complex(zeros(N_PREAM, 1));' newline ...
     '    for k = 1:N_PREAM' newline ...
     '        if mod(k,2)==1, ref(k)=complex(1,0); else, ref(k)=complex(-1,0); end' newline ...
     '    end' newline ...
     '    cv = ref'' * sym_buf;' newline ...
     '    if abs(cv) > CORR_TH' newline ...
     '        ph_corr  = conj(cv) / (abs(cv) + 1e-10);' newline ...
     '        fs_state = int32(1);' newline ...
     '        sym_idx  = int32(0);' newline ...
     '    end' newline ...
     'elseif fs_state == int32(1)' newline ...
     '    %% HEADER: 위상 보정 후 16-QAM 복조 → nibble 추출' newline ...
     '    sc  = sym * ph_corr;' newline ...
     '    nib = double(qamdemod(sc, 16, ''UnitAveragePower'', true));' newline ...
     '    if sym_idx < int32(4)' newline ...
     '        header_nibs(sym_idx + 1) = nib;' newline ...
     '    else' newline ...
     '        n0 = header_nibs(1); n1 = header_nibs(2);' newline ...
     '        n2 = header_nibs(3); n3 = header_nibs(4);' newline ...
     '        crc_rx  = nib;' newline ...
     '        crc_exp = mod(n0 + n1 + n2 + n3, 16);' newline ...
     '        if crc_rx == crc_exp' newline ...
     '            frame_cnt_rx = n0 + n1*16 + n2*256 + n3*4096;' newline ...
     '            crc_ok = true;' newline ...
     '        else' newline ...
     '            crc_ok = false;' newline ...
     '        end' newline ...
     '        fs_state = int32(2);' newline ...
     '        sym_idx  = int32(0);' newline ...
     '    end' newline ...
     '    sym_idx = sym_idx + int32(1);' newline ...
     'else' newline ...
     '    %% DATA: 위상 보정 후 출력 (CRC 통과 프레임만)' newline ...
     '    if crc_ok' newline ...
     '        data_sym   = sym * ph_corr;' newline ...
     '        data_valid = double(1);' newline ...
     '    end' newline ...
     '    sym_idx = sym_idx + int32(1);' newline ...
     '    if sym_idx >= N_DATA' newline ...
     '        fs_state = int32(0);' newline ...
     '        sym_idx  = int32(0);' newline ...
     '    end' newline ...
     'end' newline ...
     'rx_frame_cnt = frame_cnt_rx;']);
set_cplx(mdl, 'Frame Sync', 'data_sym');
px = px + step;

%% ── Outputs ──────────────────────────────────────────────────────────────────
add_block('simulink/Sinks/Out1', [mdl '/Data Sym Out'], ...
    'Position',[px 60 px+30 80], ...
    'PortDimensions','1', 'SignalType','complex');
add_block('simulink/Sinks/Out1', [mdl '/Data Valid Out'], ...
    'Port','2', ...
    'Position',[px 105 px+30 125], ...
    'PortDimensions','1', 'SignalType','real');
add_block('simulink/Sinks/Out1', [mdl '/Frame Cnt Out'], ...
    'Port','3', ...
    'Position',[px 150 px+30 170], ...
    'PortDimensions','1', 'SignalType','real');

%% ── 연결 ─────────────────────────────────────────────────────────────────────
add_line(mdl, 'RX In/1',        'AGC/1');
add_line(mdl, 'AGC/1',          'RRC MF/1');
add_line(mdl, 'RRC MF/1',       'Freq Sync/1');
add_line(mdl, 'Freq Sync/1',    'Timing Sync/1');
add_line(mdl, 'Timing Sync/1',  'Phase Sync/1');
add_line(mdl, 'Timing Sync/2',  'Phase Sync/2');
add_line(mdl, 'Phase Sync/1',   'Ch Est/1');
add_line(mdl, 'Timing Sync/2',  'Ch Est/2');
add_line(mdl, 'Ch Est/1',       'MMSE EQ/1');
add_line(mdl, 'Ch Est/2',       'MMSE EQ/2');
add_line(mdl, 'MMSE EQ/1',      'Frame Sync/1');
add_line(mdl, 'Timing Sync/2',  'Frame Sync/2');
add_line(mdl, 'Frame Sync/1',   'Data Sym Out/1');
add_line(mdl, 'Frame Sync/2',   'Data Valid Out/1');
add_line(mdl, 'Frame Sync/3',   'Frame Cnt Out/1');

set_param(mdl, 'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','1/10e6','StopTime','1e-3');
save_system(mdl, fullfile(fileparts(mfilename('fullpath')), 'rx_model.slx'));
fprintf('Saved: rx_model.slx\n');

function set_fcn(mdl, blk, script)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    ch.Script = script;
end
function set_cplx(mdl, blk, port_name)
    rt = sfroot();
    ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/' blk]);
    d  = ch.find('-isa','Stateflow.Data','Name', port_name);
    if ~isempty(d), d(1).Complexity = 'On'; end
end
