function [rx, chan_obj] = multipath_channel(tx, ch, sys)
% Frequency-selective multipath channel (ITU profiles)
%
% ch.path_delays_s  : Tap delay vector (sec)
% ch.path_gains_db  : Tap power vector (dB)
% ch.doppler_hz     : Max Doppler shift

chan_obj = comm.RayleighChannel( ...
    'SampleRate',          sys.fs, ...
    'PathDelays',          ch.path_delays_s, ...
    'AveragePathGains',    ch.path_gains_db, ...
    'MaximumDopplerShift', ch.doppler_hz, ...
    'NormalizePathGains',  true, ...
    'RandomStream',        'mt19937ar with seed', ...
    'Seed',                42);

rx = chan_obj(tx(:));
end
